# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
  Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„
  If you have screenshots [or a gif](https://publiclab.org/gifs/) to share demonstrating the issue, that's really helpful! ğŸ“¸
  Do join our [Gitter channel](https://gitter.im/publiclab/publiclab) for some brainstorming discussions. 
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request!  This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
 `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
 You can create issues [here](https://github.com/publiclab/simple-data-grapher/issues/new/choose) for any installation help
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
 Your code will likely be published to PublicLab.org in the next few days, but first it will be published to https://stable.publiclab.org/ (it will take some minutes for this to load, and until then you may see logs from the build process). Please test out your work on this testing server and report back with a comment that all has gone well!
 Do join our weekly check-in to share your this week goal and the awesome work you did ğŸ˜ƒ. Please find the link **pinned in the issue section** ğŸ“
 Now that you've completed this, you can help someone else take their first step!
 Reach out to someone else working on theirs on [Public Lab's code welcome page](https://code.publiclab.org#r=all). Thanks!
 <details>
 <summary><b>Help others take their first step</b></summary>=
 <p>Read about <a href="https://github.com/publiclab/plots2/issues/3458">how to help support another newcomer here</a>, or find <a href="https://github.com/publiclab/simple-data-grapher/labels/support">other ways to offer mutual support here</a>.</p>
 </details>
# It is recommend to include as many gifs and emojis as possible
