language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
    
before_install:
  # install forever to run daemon
  - npm install -g forever
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
dist: trusty
sudo: required

before_script: npm update
script: 
  - forever start ./node_modules/http-server/bin/http-server -p 8000
  - npm test 
